services:
  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: database
    volumes:
      - pgdb:/var/lib/postgresql

  app:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ..:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:secret@db:5432/database
      NUXT_OAUTH_KEYCLOAK_CLIENT_ID: ${NUXT_OAUTH_KEYCLOAK_CLIENT_ID}
      NUXT_OAUTH_KEYCLOAK_CLIENT_SECRET: ${NUXT_OAUTH_KEYCLOAK_CLIENT_SECRET}
      NUXT_OAUTH_KEYCLOAK_SERVER_URL: ${NUXT_OAUTH_KEYCLOAK_SERVER_URL}
      NUXT_OAUTH_KEYCLOAK_REALM: ${NUXT_OAUTH_KEYCLOAK_REALM}
volumes:
  pgdb:
